name: Cloud.py Otomatik Güncelleme

on:
  schedule:
    # Her saat başı çalıştır (UTC)
    - cron: '0 * * * *'
  workflow_dispatch:  # Manuel tetikleme butonu da olsun

jobs:
  run-cloud-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Bağımlılıkları Kur
        run: |
          pip install requests yt-dlp
      
      - name: Cloud.py Çalıştır
        env:
          # GitHub Secrets'dan ortam değişkenlerini al
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_WORKER_NAME: ${{ secrets.CF_WORKER_NAME }}
          CF_WORKER_URL: ${{ secrets.CF_WORKER_URL }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          http_proxy: "http://KULLANICI_ADI:SIFRE@IP_ADRESI:PORT"
          https_proxy: "http://KULLANICI_ADI:SIFRE@IP_ADRESI:PORT"
          no_proxy: "localhost,127.0.0.1"
        run: python Cloud.py --once
